export const POSTER_FORMATS = {
  A4X4: {
    id: 'A4X4',
    label: 'A4 com 4 cartazes',
    shortLabel: 'A4 · 4 cartazes',
    description: '4 cartazes de 10,5 × 14,9 cm',
    pickerBadge: '4 por folha',
    paper: 'A4',
    paperLabel: 'Folha A4 · 21 × 29,7 cm',
    cartSize: '10,5 × 14,9 cm',
    orientation: 'portrait',
    orientationLabel: 'Retrato',
    application: 'Gôndola e ofertas compactas',
    helpText: 'Bom para várias ofertas na mesma folha e leitura de perto.',
    widthMm: 210, heightMm: 297, postersPerSheet: 4, columns: 2, rows: 2,
    backgroundScope: 'card', invertedSlots: [],
  },
  A4X2_CIMA_BAIXO: {
    id: 'A4X2_CIMA_BAIXO',
    label: 'A4 com 2 cartazes',
    shortLabel: 'A4 · 2 cartazes',
    description: '2 cartazes de 21 × 14,9 cm',
    pickerBadge: '2 por folha',
    paper: 'A4',
    paperLabel: 'Folha A4 · 21 × 29,7 cm',
    cartSize: '21 × 14,9 cm',
    orientation: 'portrait',
    orientationLabel: 'Retrato',
    application: 'Balcão e comunicação média',
    helpText: 'Dois cartazes empilhados, um na metade superior e outro na inferior.',
    widthMm: 210, heightMm: 297, postersPerSheet: 2, columns: 1, rows: 2,
    backgroundScope: 'sheet', invertedSlots: [],
  },
  A4X2_INVERTIDO: {
    id: 'A4X2_INVERTIDO',
    label: 'A4 com 2 cartazes · invertido',
    shortLabel: 'A4 · 2 invertido',
    description: '2 cartazes de 21 × 14,9 cm',
    pickerBadge: 'superior invertido',
    paper: 'A4',
    paperLabel: 'Folha A4 · 21 × 29,7 cm',
    cartSize: '21 × 14,9 cm',
    orientation: 'portrait',
    orientationLabel: 'Retrato',
    application: 'Exposição dobrada ou frente e verso',
    helpText: 'O cartaz superior é impresso de cabeça para baixo para facilitar dobra/exposição.',
    widthMm: 210, heightMm: 297, postersPerSheet: 2, columns: 1, rows: 2,
    backgroundScope: 'sheet', invertedSlots: [0],
  },
  A4X2_APP: {
    id: 'A4X2_APP',
    label: 'A4 com 2 ofertas de App',
    shortLabel: 'A4 · 2 App',
    description: '2 ofertas lado a lado em folha A4 paisagem',
    pickerBadge: 'oferta de aplicativo',
    paper: 'A4',
    paperLabel: 'Folha A4 · 29,7 × 21 cm',
    cartSize: '14,9 × 21 cm',
    orientation: 'landscape',
    orientationLabel: 'Paisagem',
    application: 'Oferta exclusiva de aplicativo',
    helpText: 'Modelo com preço do App, validade e preço fora do aplicativo.',
    widthMm: 297, heightMm: 210, postersPerSheet: 2, columns: 2, rows: 1,
    backgroundScope: 'sheet', specialLayout: 'app-offer', invertedSlots: [],
  },
  A4: {
    id: 'A4',
    label: '1 cartaz A4',
    shortLabel: 'A4',
    description: '1 cartaz de 21 × 29,7 cm',
    pickerBadge: '1 por folha',
    paper: 'A4',
    paperLabel: 'Folha A4 · 21 × 29,7 cm',
    cartSize: '21 × 29,7 cm',
    orientation: 'portrait',
    orientationLabel: 'Retrato',
    application: 'Vitrine, ponta e leitura à distância',
    helpText: 'Cartaz grande com maior destaque para produto e preço.',
    widthMm: 210, heightMm: 297, postersPerSheet: 1, columns: 1, rows: 1,
    backgroundScope: 'card', invertedSlots: [],
  },
  A5: {
    id: 'A5',
    label: '1 cartaz A5',
    shortLabel: 'A5',
    description: '1 cartaz de 14,8 × 21 cm',
    pickerBadge: 'A5',
    paper: 'A5',
    paperLabel: 'Folha A5 · 14,8 × 21 cm',
    cartSize: '14,8 × 21 cm',
    orientation: 'portrait',
    orientationLabel: 'Retrato',
    application: 'Gôndola e balcão',
    helpText: 'Formato compacto para impressão direta em papel A5.',
    widthMm: 148, heightMm: 210, postersPerSheet: 1, columns: 1, rows: 1,
    backgroundScope: 'card', invertedSlots: [],
  },
  A3: {
    id: 'A3',
    label: '1 cartaz A3',
    shortLabel: 'A3',
    description: '1 cartaz de 29,7 × 42 cm',
    pickerBadge: 'A3',
    paper: 'A3',
    paperLabel: 'Folha A3 · 29,7 × 42 cm',
    cartSize: '29,7 × 42 cm',
    orientation: 'portrait',
    orientationLabel: 'Retrato',
    application: 'Vitrine e leitura à distância',
    helpText: 'Maior formato disponível; exige impressora ou papel A3.',
    widthMm: 297, heightMm: 420, postersPerSheet: 1, columns: 1, rows: 1,
    backgroundScope: 'card', invertedSlots: [],
  },
}

export const POSTER_FORMAT_OPTIONS = Object.values(POSTER_FORMATS)
export function getPosterFormat(formatId) { return POSTER_FORMATS[formatId] || POSTER_FORMATS.A4X4 }
export function getPageCount(productCount, format) { return productCount ? Math.ceil(productCount / format.postersPerSheet) : 1 }
