// Fonte única de conteúdo/SEO para runtime, sitemap e páginas estáticas.
// PRODUCT_DECISION_AI_UPCOMING: IA é próxima implementação; não anunciar como recurso disponível.
export const SITE_URL = 'https://ofertamatica.com.br'

export const PUBLIC_PAGES = [
  {
    kind: 'public',
    slug: 'modelos',
    title: 'Modelos de Placas de Preço Grátis para Mercado | Ofertamática',
    description: 'Escolha modelos de cartazes para mercado e supermercado. Personalize preço, cores, cabeçalho e logo da loja e prepare placas prontas para imprimir.',
    keywords: 'modelos de cartaz de oferta, modelo cartaz supermercado, modelo placa de preço',
    eyebrow: 'MODELOS',
    heading: 'Modelos para destacar cada tipo de oferta',
    lead: 'Escolha uma base visual e adapte cores, cabeçalho e conteúdo para a campanha ou departamento da sua loja.',
    benefits: ['Vários estilos prontos', 'Cores e cabeçalhos personalizáveis', 'Aplicação direta no editor'],
  },
  {
    kind: 'public',
    slug: 'formatos',
    title: 'Cartaz A4, A5 e A3 para Imprimir | Ofertamática',
    description: 'Compare tamanhos A7, A6, A5, A4 e A3 para criar cartazes de preço. Aproveite várias placas por folha e imprima no formato ideal para sua loja.',
    keywords: 'formato cartaz A4, cartaz A5, cartaz A3, tamanho cartaz oferta',
    eyebrow: 'FORMATOS',
    heading: 'Escolha o formato certo para cada espaço da loja',
    lead: 'Compare tamanho físico, quantidade por folha e distância de leitura antes de iniciar a criação.',
    benefits: ['A4 com 1, 2 ou 4 cartazes', 'A5 e A3', 'Pré-visualização antes da impressão'],
  },
  {
    kind: 'public',
    slug: 'qual-papel-usar-para-cartaz',
    title: 'Qual Papel Usar para Cartaz de Oferta? A4, A5, A3 | Ofertamática',
    description: 'Saiba qual papel usar para imprimir cartazes de supermercado: sulfite, offset ou papel mais encorpado, gramaturas e formatos A4, A5 e A3.',
    keywords: 'qual papel usar para cartaz de oferta, papel para cartaz de supermercado, papel para imprimir cartaz A4, gramatura para cartaz de preço',
    eyebrow: 'GUIA DE PAPEL E IMPRESSÃO',
    heading: 'Qual papel usar para imprimir cartazes de oferta?',
    lead: 'Entenda a diferença entre tamanho da folha e gramatura do papel. Escolha A4, A5 ou A3 para a sua impressora e use a espessura adequada ao local de exposição.',
    benefits: ['A4, A5 e A3 explicados', 'Gramatura conforme uso', 'Configuração de impressão sem distorção'],
    sections: [
      {
        title: 'Papel sulfite ou offset para ofertas do dia a dia',
        text: 'Para placas de preço trocadas com frequência, papel branco comum de aproximadamente 75 a 90 g/m² é uma escolha econômica. Confirme a compatibilidade com a impressora e faça uma prova de cor, pois papéis mais finos podem ficar transparentes com grandes áreas coloridas.',
      },
      {
        title: 'Papel mais encorpado para vitrines, pontas e balcões',
        text: 'Para um cartaz que precisa ter mais firmeza, avalie papel fosco mais encorpado, por exemplo na faixa de 120 a 180 g/m², sempre dentro da especificação da sua impressora. Papéis couchê exigem atenção à compatibilidade de tinta ou toner e ao acabamento; nem todo couchê funciona bem em impressoras comuns.',
      },
      {
        title: 'Qual folha escolher: A4, A5 ou A3',
        text: 'O tamanho da folha não é a mesma coisa que a gramatura. A4 mede 21 × 29,7 cm e permite imprimir um cartaz grande, dois, quatro ou oito cartazes menores. A5 mede 14,8 × 21 cm e é útil para comunicação próxima. A3 mede 29,7 × 42 cm, oferece mais área e depende de impressora compatível.',
      },
      {
        title: 'Os cartazes A6 e A7 são feitos em folha A4',
        text: 'No gerador, as opções de quatro cartazes A6 e oito cartazes A7 usam uma única folha A4. Não é necessário comprar folhas A6 ou A7 para essas opções: imprima a folha A4 e corte os cartazes. Confira as margens da impressora antes de recortar.',
      },
      {
        title: 'Como imprimir sem reduzir o preço e o cabeçalho',
        text: 'Na janela de impressão, escolha o mesmo papel configurado no cartaz, confirme retrato ou paisagem e use escala de 100% ou tamanho real. Desative cabeçalhos e rodapés do navegador. Evite “Ajustar à página” quando precisar preservar as dimensões físicas; se a impressora não aceitar a área de impressão, revise margens e faça uma prova.',
      },
      {
        title: 'Teste antes de imprimir várias placas',
        text: 'Imprima um exemplo, verifique se a tinta seca, se há contraste suficiente no preço, se o texto não foi cortado e se o material pode ser colocado no suporte da loja. Para cartazes expostos ao sol, à umidade ou ao manuseio frequente, considere proteção adequada ao ambiente.',
      },
    ],
    paperChoices: [
      { label: 'Rotina de gôndola', paper: 'Papel sulfite ou offset branco', weight: '75–90 g/m² (referência)', why: 'Bom custo para cartazes trocados com frequência' },
      { label: 'Balcão e ponta de gôndola', paper: 'Papel fosco mais firme', weight: '120–150 g/m² (referência)', why: 'Maior rigidez e melhor apresentação quando compatível' },
      { label: 'Vitrine e campanhas', paper: 'Papel fosco ou cartão apropriado', weight: '150–180 g/m² (referência)', why: 'Mais corpo; confira se sua impressora aceita' },
    ],
    formatChoices: [
      { id: 'A4X8', name: '8 cartazes A7', sheet: 'A4 · 21 × 29,7 cm', area: '10,5 × 7,4 cm cada', use: 'Gôndola e etiquetas maiores' },
      { id: 'A4X4', name: '4 cartazes A6', sheet: 'A4 · 21 × 29,7 cm', area: '10,5 × 14,9 cm cada', use: 'Gôndola e ofertas compactas' },
      { id: 'A4X2_CIMA_BAIXO', name: '2 cartazes por folha', sheet: 'A4 · 21 × 29,7 cm', area: '21 × 14,9 cm cada', use: 'Balcão, ilha ou ponta' },
      { id: 'A4', name: '1 cartaz A4', sheet: 'A4 · 21 × 29,7 cm', area: '21 × 29,7 cm', use: 'Ponta e cartaz de destaque' },
      { id: 'A5', name: '1 cartaz A5', sheet: 'A5 · 14,8 × 21 cm', area: '14,8 × 21 cm', use: 'Balcão e espaços menores' },
      { id: 'A3', name: '1 cartaz A3', sheet: 'A3 · 29,7 × 42 cm', area: '29,7 × 42 cm', use: 'Vitrine e leitura mais distante' },
    ],
    printSteps: [
      'Selecione no Ofertamática o formato correspondente à folha que a impressora aceita.',
      'Gere as placas e revise descrição, unidade, preço e texto do cabeçalho.',
      'Abra Imprimir ou Salvar PDF e selecione o mesmo tamanho de papel usado no editor.',
      'Confira a orientação, desative os cabeçalhos do navegador e mantenha 100% de escala.',
      'Faça uma impressão de teste antes de produzir várias folhas.',
    ],
    faq: [
      { q: 'Qual a melhor gramatura de papel para cartaz de oferta?', a: 'Para ofertas trocadas diariamente, 75–90 g/m² costuma ser suficiente. Para cartazes que precisam ficar mais firmes, avalie 120–180 g/m², desde que a impressora suporte esse papel.' },
      { q: 'Preciso comprar papel A6 ou A7 para imprimir várias placas?', a: 'Não para os layouts A4 com quatro ou oito cartazes do Ofertamática. Eles usam papel A4; depois da impressão, basta recortar nas divisões.' },
      { q: 'Posso imprimir cartaz A3 em impressora A4?', a: 'Não no tamanho físico A3. Para imprimir em 29,7 × 42 cm você precisa de uma impressora ou serviço gráfico compatível com A3. Reduzir para A4 altera o tamanho final.' },
      { q: 'Papel couchê funciona em qualquer impressora?', a: 'Não. A compatibilidade depende do papel, da tinta ou do toner e das especificações do equipamento. Verifique o manual da impressora ou procure uma gráfica.' },
      { q: 'Por que o cartaz sai menor do que o tamanho escolhido?', a: 'Isso costuma ocorrer quando a janela de impressão está em “Ajustar à página” ou usa papel diferente do selecionado. Confira o tamanho da folha, a orientação, as margens e a escala de 100%.' },
    ],
    links: [
      { label: 'Comparar tamanhos dos cartazes', href: '/formatos/', note: 'Veja os layouts em A4, A5 e A3.' },
      { label: 'Criar cartaz de oferta para imprimir', href: '/cartaz-de-oferta-para-imprimir/', note: 'Do gerador ao PDF e à impressora.' },
      { label: 'Ver modelos de cartazes', href: '/modelos/', note: 'Escolha a arte antes de imprimir.' },
    ],
  },
  {
    kind: 'public',
    slug: 'como-funciona',
    title: 'Como Fazer Placas para Mercado Online | Ofertamática',
    description: 'Aprenda a criar placas de preço e cartazes de supermercado: escolha o formato, cole produtos ou importe uma planilha, gere em lote e imprima grátis.',
    keywords: 'como criar cartaz de oferta, como funciona Ofertamática, criar placa de preço',
    eyebrow: 'COMO FUNCIONA',
    heading: 'Da lista de produtos à placa pronta em 2 cliques',
    lead: 'Escolha o formato, cole sua lista e gere. O resultado aparece antes de qualquer personalização obrigatória.',
    benefits: ['Primeira placa em 2 cliques', 'Sem cadastro para começar', 'Personalização opcional depois do resultado'],
  },
  {
    kind: 'public',
    slug: 'guias-para-varejo',
    title: 'Como Fazer Cartazes de Supermercado | Guias Ofertamática',
    description: 'Guias gratuitos para fazer placas de preço de mercado, criar cartazes de promoção e imprimir ofertas A4, A5 e A3 com boa legibilidade.',
    keywords: 'guias varejo, cartaz supermercado, cartaz promoção, cartaz para imprimir',
    eyebrow: 'GUIAS PARA VAREJO',
    heading: 'Guias práticos para melhorar a comunicação de ofertas',
    lead: 'Conteúdos práticos sobre criação, preço, formatos, impressão e comunicação de ofertas no varejo.',
    benefits: ['Tutoriais por necessidade', 'Links para formatos e modelos', 'Acesso gratuito ao criador'],
    sections: [
      { title: 'Por onde começar a preparar as placas de preço', text: 'Se você já tem uma lista de produtos, comece pelo criador ou pelo guia de importação de planilhas. Confira nome, peso ou volume, preço e condições da oferta antes de gerar o lote. Para quem trabalha no mercado diariamente, manter um padrão de cabeçalho, contraste e tamanho reduz retrabalho e facilita a conferência da campanha.' },
      { title: 'Como escolher cartazes para cada setor', text: 'Os guias para supermercado, açougue e padaria tratam da diferença entre preço por kg, por unidade e por embalagem. Ao preparar uma oferta relâmpago, uma placa De/Por ou uma campanha de atacado e varejo, descreva a regra da promoção com clareza e confira se o cliente consegue reconhecer a informação principal.' },
      { title: 'Papel, tamanho e PDF na rotina da loja', text: 'Antes de imprimir, escolha entre A4, A5 e A3 segundo a distância de leitura e a impressora disponível. O guia de papel explica gramaturas comuns e como evitar escala incorreta, margens inesperadas ou cortes. Você também pode salvar o cartaz como PDF pela impressão do navegador quando essa opção estiver disponível.' },
    ],
  },
  {
    kind: 'public',
    slug: 'sobre',
    title: 'Sobre o Ofertamática | Ferramenta para Cartazes de Oferta',
    description: 'Conheça o propósito do Ofertamática, como a ferramenta foi pensada para o varejo e os princípios usados no desenvolvimento do produto.',
    keywords: 'sobre Ofertamática, ferramenta cartaz de oferta, software varejo',
    eyebrow: 'SOBRE',
    heading: 'Uma ferramenta feita para simplificar a criação de cartazes no varejo',
    lead: 'O Ofertamática simplifica a criação de placas de preço e materiais promocionais para supermercados, mercados e outros negócios do varejo.',
    benefits: ['Ferramenta focada em uso real', 'Criação sem cadastro obrigatório', 'Evolução guiada por clareza e produtividade'],
    trust: true,
    updatedAt: 'Atualizado em 8 de outubro de 2026',
    sections: [
      { title: 'Por que o Ofertamática existe', text: 'Criar dezenas de cartazes manualmente consome tempo e aumenta a chance de inconsistências. O Ofertamática foi pensado para transformar uma lista de produtos em placas prontas para revisão, mantendo preço, produto e leitura como prioridade.' },
      { title: 'Para quem é a ferramenta', text: 'O foco são equipes de supermercado, mercados, mercearias, atacarejos e outros negócios que precisam comunicar ofertas com frequência. O fluxo também pode ser usado por pequenos lojistas que querem preparar materiais diretamente no navegador.' },
      { title: 'Como funciona na prática', text: 'O fluxo prioriza poucas etapas: escolher o formato, informar os produtos, revisar o resultado e imprimir. Personalizações continuam opcionais para não atrapalhar a criação rápida.' },
      { title: 'Compromisso com clareza', text: 'O site busca manter orientações simples, conteúdo útil e informações claras sobre impressão, privacidade e uso da ferramenta. Antes de imprimir, revise preços, unidades, validade e condições comerciais.' },
    ],
  },
  {
    kind: 'public',
    slug: 'fale-conosco',
    title: 'Fale Conosco | Ofertamática',
    description: 'Fale com a equipe da Ofertamática pelo e-mail atendimento@ofertamatica.com.br. Suporte, dúvidas, sugestões e privacidade.',
    keywords: 'contato Ofertamática, suporte Ofertamática, fale conosco',
    eyebrow: 'FALE CONOSCO',
    heading: 'Como podemos ajudar?',
    lead: 'Entre em contato pelo e-mail atendimento@ofertamatica.com.br para dúvidas, suporte, sugestões ou solicitações privadas. Consulte também nossos guias de criação e impressão.',
    benefits: ['Contato por e-mail', 'Ajuda para criar e imprimir', 'Privacidade e termos em linguagem clara'],
    trust: true,
    updatedAt: 'Atualizado em 8 de outubro de 2026',
    sections: [
      { title: 'Ajuda para criar e imprimir', text: 'Consulte Como funciona e os Guias para varejo para aprender a escolher formatos, importar listas de produtos, personalizar cartazes e imprimir.' },
      { title: 'Se alguma função não estiver funcionando', text: 'Descreva o problema no e-mail acima e, se possível, informe o navegador, o dispositivo e a etapa em que ocorreu. Não envie senhas nem listas de clientes.' },
      { title: 'Relatos técnicos públicos', text: 'O GitHub é uma alternativa para sugestões e falhas técnicas que possam ser compartilhadas publicamente. Para assuntos privados, utilize somente o contato por e-mail.' },
    ],
    links: [
      { label: 'Enviar e-mail ao atendimento', href: 'mailto:atendimento@ofertamatica.com.br?subject=Atendimento%20Ofertam%C3%A1tica', note: 'Canal oficial de suporte, dúvidas e sugestões.' },
      { label: 'Como funciona', href: '/como-funciona/', note: 'Passo a passo para criar, revisar e imprimir.' },
      { label: 'Guias para varejo', href: '/guias-para-varejo/', note: 'Boas práticas de preço, formatos e comunicação.' },
      { label: 'Política de Privacidade', href: '/privacidade/', note: 'Como dados, armazenamento local e anúncios são tratados.' },
      { label: 'Relatar problema técnico no GitHub', href: 'https://github.com/HelioConde/ofertamatica/issues/new', note: 'Canal público para reportar falhas ou sugerir melhorias. Não envie dados privados.' },
    ],
  },
  {
    kind: 'public',
    slug: 'privacidade',
    title: 'Política de Privacidade | Ofertamática',
    description: 'Entenda como o Ofertamática usa armazenamento local, analytics, publicidade e dados técnicos durante o uso do site.',
    keywords: 'privacidade Ofertamática, política de privacidade',
    eyebrow: 'PRIVACIDADE',
    heading: 'Privacidade e uso de dados no Ofertamática',
    lead: 'A criação de placas pode começar sem cadastro. Esta página explica quais dados ficam no dispositivo, quais serviços externos podem processar dados técnicos e como entrar em contato.',
    benefits: ['Criação sem cadastro obrigatório', 'Rascunhos salvos localmente', 'Transparência sobre analytics e publicidade'],
    legal: true,
    updatedAt: 'Atualizado em 8 de outubro de 2026',
    sections: [
      { title: 'Rascunhos e preferências', text: 'O editor usa o armazenamento local do navegador para manter o último trabalho, listas recentes, formato escolhido e preferências de personalização no dispositivo. Esses dados não formam um cadastro de conta e podem ser apagados limpando os dados do site no navegador.' },
      { title: 'Arquivos importados', text: 'Arquivos TXT, CSV, XLS ou XLSX selecionados no editor são lidos para preencher a lista de produtos. O fluxo atual não exige uma conta para essa importação e a ferramenta foi projetada para realizar essa preparação no navegador.' },
      { title: 'Medição de uso e desempenho', text: 'O site pode usar ferramentas de medição para entender quais páginas são acessadas, como os recursos são utilizados e onde a experiência pode melhorar. Essas medições não criam uma conta no Ofertamática.' },
      { title: 'Publicidade e cookies', text: 'Áreas específicas podem exibir anúncios do Google AdSense. O Google e seus parceiros podem usar cookies ou tecnologias equivalentes para entregar, medir e proteger anúncios conforme suas políticas e as escolhas de consentimento aplicáveis.' },
      { title: 'Serviços externos', text: 'Serviços de medição e publicidade podem processar informações técnicas do navegador e do dispositivo de acordo com suas próprias políticas e requisitos legais.' },
      { title: 'Contato e solicitações', text: 'Para dúvidas sobre privacidade, pedidos de correção ou outros assuntos relacionados aos seus dados, escreva para atendimento@ofertamatica.com.br. Não compartilhe senhas nem dados sensíveis em canais públicos.' },
    ],
    links: [
      { label: 'Solicitar atendimento sobre privacidade', href: 'mailto:atendimento@ofertamatica.com.br?subject=Privacidade%20-%20Ofertam%C3%A1tica', note: 'Entre em contato diretamente com a equipe.' },
      { label: 'Fale conosco', href: '/fale-conosco/', note: 'Outros canais e orientações.' },
    ],
  },
  {
    kind: 'public',
    slug: 'termos',
    title: 'Termos de Uso | Ofertamática',
    description: 'Consulte as condições gerais de uso do criador de cartazes Ofertamática.',
    keywords: 'termos Ofertamática, termos de uso',
    eyebrow: 'TERMOS DE USO',
    heading: 'Condições de uso do Ofertamática',
    lead: 'O Ofertamática é uma ferramenta de apoio à criação e impressão de comunicação promocional. O usuário continua responsável pela revisão das informações comerciais.',
    benefits: ['Revise preços antes de imprimir', 'Use conteúdos e marcas com autorização', 'A ferramenta pode evoluir continuamente'],
    legal: true,
    updatedAt: 'Atualizado em 8 de outubro de 2026',
    sections: [
      { title: 'Revisão das informações', text: 'Antes de imprimir ou publicar qualquer material, confira produto, preço, unidade, validade, condições promocionais e demais informações. A revisão final é responsabilidade de quem utiliza a ferramenta.' },
      { title: 'Conteúdo utilizado', text: 'Ao inserir textos, logotipos, imagens ou outros materiais, utilize conteúdo que você tenha autorização para usar e respeite direitos de terceiros.' },
      { title: 'Disponibilidade', text: 'O serviço pode receber melhorias, correções, novos formatos e mudanças de interface. Recursos podem ser alterados, substituídos ou temporariamente ficar indisponíveis para melhorar segurança, desempenho ou usabilidade.' },
      { title: 'Uso adequado', text: 'Não utilize o serviço para práticas ilícitas, fraude, conteúdo enganoso, violação de direitos ou qualquer finalidade que descumpra a legislação aplicável.' },
      { title: 'Publicidade e serviços externos', text: 'O site pode exibir anúncios e usar serviços externos de medição. Esses serviços são identificados na Política de Privacidade e funcionam conforme as políticas de seus respectivos provedores.' },
      { title: 'Contato', text: 'Dúvidas sobre os termos, relatos de erro ou questões relacionadas a conteúdo e privacidade podem ser enviados a atendimento@ofertamatica.com.br.' },
    ],
    links: [
      { label: 'Entrar em contato por e-mail', href: 'mailto:atendimento@ofertamatica.com.br?subject=Termos%20de%20Uso%20-%20Ofertam%C3%A1tica', note: 'Dúvidas sobre as condições de uso e o serviço.' },
      { label: 'Fale conosco', href: '/fale-conosco/', note: 'Ajuda e outras informações.' },
    ],
  },
]

export const SEO_PAGES = [
  {
    kind: 'seo',
    group: 'Setores',
    slug: 'placas-para-padaria',
    title: 'Placas de Preço para Padaria Grátis | Ofertamática',
    description: 'Crie placas de preço para padaria, pães, bolos e salgados. Destaque valor, peso ou unidade e imprima cartazes A4 e A5 gratuitamente.',
    keywords: 'placas para padaria, cartazes de preço para padaria, cartaz de oferta pão, preço por kg padaria',
    eyebrow: 'CARTAZES PARA PADARIA',
    heading: 'Crie placas de preço para padaria com leitura fácil',
    lead: 'Prepare cartazes para pães, bolos, salgados e ofertas do balcão. Monte sua lista de produtos, informe preços e unidades e gere placas com uma identidade visual consistente.',
    benefits: ['Preço por kg, unidade ou embalagem bem identificado', 'Formatos A4 e A5 para balcão e vitrines', 'Geração de várias placas na mesma lista'],
    sections: [
      { title: 'Como escrever o preço do pão sem confundir o cliente', text: 'Confira se o preço informado é por quilo, por unidade ou por pacote. Produtos vendidos por peso precisam deixar essa condição clara no cartaz, especialmente quando há preços diferentes para variedades de pães. Informe o nome reconhecível do produto e revise se a unidade corresponde ao preço do sistema da loja.' },
      { title: 'Bolos, salgados e itens de produção própria', text: 'Para um bolo vendido por pedaço, não use a mesma unidade que um bolo vendido por quilo. Se a oferta vale apenas para um sabor, tamanho ou variedade, escreva a condição no complemento da descrição. Ao imprimir várias placas, confira cada item individualmente antes de colocá-lo na vitrine.' },
      { title: 'Qual formato usar no balcão da padaria', text: 'Placas A5 são práticas quando o consumidor está próximo do balcão. A4 pode ser útil em uma área de ofertas ou cartazes de maior destaque. Evite reduzir demais o texto para acomodar muitos produtos em uma folha: economizar papel não deve comprometer a leitura do preço e da unidade.' },
      { title: 'Exemplo de lista para gerar os cartazes', text: 'Você pode preparar uma lista demonstrativa com “PÃO FRANCÊS KG 14,99”, “BOLO DE CENOURA FATIA 6,50” e “COXINHA UN 5,99”, substituindo pelos preços verdadeiros da loja. Após gerar, revise os campos de descrição, unidade e preço, ajuste o cabeçalho de padaria e veja a prévia antes de imprimir.' },
    ],
    tips: ['Diferencie preço por kg de preço por unidade.', 'Informe variações relevantes como sabor, peso ou tamanho.', 'Revise validade e condições comerciais antes de expor o cartaz.'],
    storeUse: ['Balcão de pães: placas próximas com unidade de venda explícita.', 'Vitrine de bolos: identifique fatia, unidade ou kg.', 'Ofertas da semana: mantenha o mesmo cabeçalho nas placas da campanha.'],
    links: [
      { label: 'Modelos de cartazes', href: '/modelos/', note: 'Escolha cores e cabeçalhos para a padaria.' },
      { label: 'Qual papel usar', href: '/qual-papel-usar-para-cartaz/', note: 'Compare tamanhos e gramaturas antes da impressão.' },
      { label: 'Criar placas grátis', href: '/', note: 'Abra o gerador sem cadastro.' },
    ],
  },
  {
    kind: 'seo',
    group: 'Guias',
    slug: 'cartazes-a-partir-de-excel',
    title: 'Criar Cartazes a Partir do Excel Grátis | Ofertamática',
    description: 'Importe produtos de Excel, CSV ou TXT e transforme a lista em cartazes de oferta. Revise preço e descrição, gere em lote e imprima grátis.',
    keywords: 'excel para cartazes, cartazes a partir de excel, importar produtos excel, fazer placas de preço por planilha',
    eyebrow: 'CARTAZES COM PLANILHAS',
    heading: 'Transforme uma lista do Excel em cartazes de oferta',
    lead: 'Evite digitar produtos um por um: organize a planilha, importe os dados no Ofertamática, revise a interpretação dos preços e gere várias placas prontas para impressão.',
    benefits: ['Importação de XLS, XLSX, CSV e TXT', 'Criação em lote no navegador', 'Revisão antes de imprimir ou salvar em PDF'],
    sections: [
      { title: 'Prepare a planilha com nomes e preços corretos', text: 'Antes de importar, confira se cada produto tem descrição reconhecível, valor atualizado e unidade de venda. Evite linhas vazias com totais, códigos internos sem descrição e colunas misturando preço de custo com preço ao consumidor. Faça uma cópia do arquivo para trabalhar sem alterar seu cadastro original.' },
      { title: 'Importe e revise a lista no gerador', text: 'Abra o Ofertamática e escolha o formato de papel. Cole os produtos diretamente na entrada rápida ou use a opção de importar arquivo, conforme o tipo de planilha disponível. Depois da leitura, confira os itens interpretados; formatos de números e separadores podem variar entre arquivos.' },
      { title: 'Corrija preços, unidades e observações antes de gerar', text: 'A importação acelera o trabalho, mas não substitui a revisão humana. Confirme vírgulas decimais, indicação de kg, ml ou unidade, promoções De/Por e condições de atacado. Informações de validade, limites por cliente e logotipos podem exigir personalização adicional.' },
      { title: 'Escolha um layout de impressão adequado', text: 'Para ofertas grandes em ponta de gôndola, avalie A4 inteiro ou A3. Se as placas serão lidas de perto, é possível aproveitar uma folha A4 com várias placas menores. Abra a prévia, verifique cortes e acentuação e só então imprima ou escolha salvar como PDF na janela do navegador.' },
      { title: 'Exemplo prático de lista', text: 'Uma lista demonstrativa pode conter “ARROZ BRANCO 1 KG 5,99”, “CAFÉ TORRADO 500 G 18,90” e “LEITE INTEGRAL 1 L 4,79”. O objetivo é mostrar descrições, quantidade e preços separados de forma clara; substitua os exemplos pelos dados reais da loja e valide o resultado.' },
    ],
    tips: ['Use uma cópia revisada da planilha.', 'Confira separadores decimais e unidades.', 'Sempre compare a prévia com a lista original antes de imprimir.'],
    storeUse: ['Ofertas semanais: gere vários cartazes sem redigitar.', 'Setores diferentes: aplique modelos depois da importação.', 'Reimpressão: revise preços e condições que possam ter mudado.'],
    links: [
      { label: 'Como funciona o gerador', href: '/como-funciona/', note: 'Entenda as etapas de criação.' },
      { label: 'Formatos disponíveis', href: '/formatos/', note: 'Escolha quantos cartazes cabem em cada folha.' },
      { label: 'Abrir gerador de cartazes', href: '/', note: 'Comece gratuitamente.' },
    ],
  },

  {
    kind: 'seo',
    group: 'Setores',
    slug: 'cartazes-para-acougue',
    title: 'Cartazes para Açougue Grátis | Placas de Preço Online',
    description: 'Faça cartazes para açougue grátis: indique corte, preço por kg e validade. Gere placas em lote, revise o layout e imprima em A4, A5 ou A3.',
    keywords: 'cartazes para açougue, cartaz de preço carne, placa de oferta açougue',
    eyebrow: 'CARTAZES PARA AÇOUGUE',
    heading: 'Cartazes de ofertas para açougue com preço por quilo legível',
    lead: 'Monte placas para cortes bovinos, suínos e aves, mantendo o nome do corte, a unidade de venda e o preço em destaque. Gere a lista de ofertas e revise cada cartaz antes de imprimir.',
    benefits: ['Preço por kg e descrição do corte', 'Formatos para balcão e área promocional', 'Várias placas em um único trabalho'],
    sections: [
      { title: 'O que colocar no cartaz do açougue', text: 'Escreva o nome do corte, sua apresentação e a unidade de venda, como kg ou bandeja. Confira se o preço apresentado corresponde à unidade anunciada e indique eventuais condições comerciais aplicáveis.' },
      { title: 'Qual tamanho usar no balcão', text: 'A5 e A4 atendem leituras próximas no balcão. A3 pode ser útil em pontos mais distantes. Escolha o formato conforme o espaço e confira a prévia antes de imprimir.' },
      { title: 'Como criar várias ofertas de carne', text: 'Cole uma lista com um produto e seu preço por linha, gere as placas e personalize o cabeçalho ou a cor quando necessário. Confira as informações comerciais antes de expor os cartazes.' },
    ],
    tips: ['Informe se o preço é por kg ou por unidade.', 'Evite abreviar cortes de maneira ambígua.', 'Revise preços, validade e disponibilidade antes de imprimir.'],
    storeUse: ['Balcão de carnes: comunicação simples e próxima.', 'Ilhas de congelados: nome e quantidade claramente identificados.', 'Campanhas de fim de semana: placas padronizadas para diferentes cortes.'],
    links: [{ label: 'Criar cartazes agora', href: '/', note: 'Abra o gerador gratuito.' }, { label: 'Cartazes para supermercado', href: '/cartaz-para-supermercado/', note: 'Explore outras áreas da loja.' }],
  },
  {
    kind: 'seo',
    group: 'Criação',
    slug: 'criador-de-cartaz-de-oferta',
    title: 'Criador de Placas de Preço Online Grátis | Ofertamática',
    description: 'Crie placas de oferta e cartazes de preço grátis no navegador. Cole produtos, gere várias placas em lote e personalize antes de imprimir.',
    keywords: 'criador de cartaz de oferta, criar cartaz de oferta, cartaz promocional, placa de oferta',
    eyebrow: 'CRIADOR DE CARTAZ DE OFERTA',
    heading: 'Escolha o formato, cole a lista e tenha as placas prontas',
    lead: 'O fluxo principal tem só 2 cliques. Depois do resultado, você pode personalizar header, cores e tipos de promoção sem bloquear a criação.',
    benefits: ['2 cliques para gerar', 'Várias placas por vez', 'Personalização opcional depois'],
    tips: ['Escolha o formato pela distância de leitura.', 'Mantenha a descrição curta e reconhecível.', 'Revise preço e unidade antes de imprimir.'],
    storeUse: ['Cole dezenas de produtos de uma vez para reduzir digitação repetitiva.', 'Revise somente o que precisa de correção antes de imprimir.', 'Mantenha a prévia visível enquanto ajusta preço, unidade e cabeçalho.'],
  },
  {
    kind: 'seo',
    group: 'Supermercado',
    slug: 'cartaz-para-supermercado',
    title: 'Cartaz para Supermercado Grátis | Criar e Imprimir',
    description: 'Faça cartaz para mercado grátis: placas de preço para supermercado, mercearia e atacarejo. Edite ofertas, gere em lote e imprima online.',
    keywords: 'cartaz para supermercado, cartaz supermercado, cartaz para mercado, placa de preço supermercado',
    eyebrow: 'CARTAZ PARA SUPERMERCADO',
    heading: 'Cartazes de supermercado sem perder tempo formatando',
    lead: 'Organize ofertas para gôndolas, hortifruti, açougue, padaria, bebidas e outros setores em um padrão visual consistente.',
    benefits: ['Preço em destaque', '6 tipos de oferta opcionais', 'Logo, validade e limite opcionais'],
    tips: ['Use cartazes menores para gôndola e maiores para ponta/vitrine.', 'Agrupe campanhas por setor para manter consistência.', 'Evite excesso de texto concorrendo com o preço.'],
    storeUse: ['Gôndola: placas compactas e leitura próxima.', 'Ilhas e pontas: preço maior e menos texto.', 'Setores como hortifruti, açougue e padaria podem usar cabeçalhos próprios mantendo o mesmo padrão de preço.'],
  },
  {
    kind: 'seo',
    group: 'Campanhas',
    slug: 'gerador-de-cartaz-de-promocao',
    title: 'Gerador de Cartaz de Promoção Grátis | Ofertamática',
    description: 'Crie cartaz de oferta editável, De/Por, atacado e varejo e campanhas de fim de semana. Personalize o preço e imprima suas promoções grátis.',
    keywords: 'gerador de cartaz de promoção, cartaz de promoção online, criar promoção, cartaz promocional',
    eyebrow: 'GERADOR DE CARTAZ DE PROMOÇÃO',
    heading: 'Transforme sua lista de promoções em cartazes',
    lead: 'Crie comunicação promocional clara para ofertas recorrentes e campanhas sazonais sem começar o layout do zero.',
    benefits: ['Criação em lote', 'Cabeçalhos promocionais', 'Formatos para diferentes pontos da loja'],
    tips: ['Use um cabeçalho coerente com a campanha.', 'Destaque uma condição promocional por cartaz.', 'Padronize os cartazes da mesma ação.'],
    storeUse: ['Crie uma sequência inteira com o mesmo header para uma campanha.', 'Troque produtos e preços sem reconstruir o layout.', 'Use campanhas sazonais e ofertas relâmpago mantendo consistência visual.'],
  },
  {
    kind: 'seo',
    group: 'Preço',
    slug: 'cartaz-de-preco-online',
    title: 'Placas de Preço para Mercado Online | Ofertamática',
    description: 'Use o criador de placas de preço online para destacar produto, unidade e valor. Gere cartazes de supermercado gratuitamente e imprima.',
    keywords: 'cartaz de preço online, placa de preço, criar cartaz de preço, preço para imprimir',
    eyebrow: 'CARTAZ DE PREÇO ONLINE',
    heading: 'Preço legível e produto fácil de identificar',
    lead: 'Organize produto, complemento, unidade e valor com uma hierarquia visual pensada para leitura rápida.',
    benefits: ['Preço com destaque automático', 'Campos editáveis', 'Pré-visualização antes da impressão'],
    tips: ['Confira se unidade e gramatura correspondem ao preço.', 'Evite abreviações pouco conhecidas.', 'Use contraste forte entre fundo e preço.'],
    storeUse: ['O preço deve ser o elemento de maior leitura à distância.', 'Produto e unidade precisam continuar identificáveis em poucos segundos.', 'Contraste alto ajuda a leitura em corredores, ilhas e áreas promocionais.'],
  },
  {
    kind: 'seo',
    group: 'Impressão',
    slug: 'cartaz-de-oferta-para-imprimir',
    title: 'Cartaz de Oferta para Imprimir Grátis | A4, A5 e A3',
    description: 'Crie cartazes e placas de preço para imprimir grátis em A4, A5 e A3, com opções A6 e A7 por folha. Confira a prévia e salve em PDF.',
    keywords: 'cartaz de oferta para imprimir, cartaz A4 para imprimir, placa de oferta imprimir, cartaz A3',
    eyebrow: 'CARTAZ PARA IMPRIMIR',
    heading: 'Crie no navegador e imprima no tamanho certo',
    lead: 'Escolha o papel, confira a orientação e revise o resultado visual antes de abrir a janela de impressão.',
    benefits: ['A7, A6, A5, A4 e A3', '1, 2, 4 ou 8 cartazes por folha A4', 'Revisão de impressão integrada'],
    tips: ['Use escala de 100% na impressão.', 'Desative cabeçalhos e rodapés do navegador.', 'Confira papel e orientação antes de confirmar.'],
    storeUse: ['Revise o tamanho físico antes de abrir a janela de impressão.', 'Use vários cartazes por folha quando a leitura for próxima.', 'Prefira cartazes maiores para vitrines, pontas e comunicação suspensa.'],
  },
  {
    kind: 'seo',
    group: 'Impressão',
    slug: 'cartaz-a4',
    title: 'Cartaz de Oferta A4 Grátis para Imprimir | Ofertamática',
    description: 'Faça cartaz de oferta A4 grátis, com uma, duas, quatro ou oito placas por folha. Revise o preço, personalize e imprima no tamanho certo.',
    keywords: 'cartaz A4, cartaz A4 oferta, cartaz A4 para imprimir, placa de preço A4',
    eyebrow: 'FORMATO A4',
    heading: 'Cartazes A4 para diferentes espaços da loja',
    lead: 'Use uma folha inteira para maior impacto ou aproveite o A4 com duas, quatro A6 ou oito A7 para economizar papel.',
    benefits: ['A4 com 1 cartaz', 'A4 com 2 cartazes', '4 A6 ou 8 A7 por folha'],
    tips: ['A4 inteiro funciona melhor à distância.', 'Dois por folha equilibram impacto e economia.', 'A6 e A7 funcionam melhor em leitura próxima e economizam papel.'],
    storeUse: ['A4 inteiro: maior impacto visual.', 'A4 com 2 placas: equilíbrio entre economia e leitura.', 'A6 com 4 e A7 com 8: melhor aproveitamento para gôndolas e pontos próximos.'],
  },
  {
    kind: 'seo',
    group: 'Campanhas',
    slug: 'cartaz-de-por',
    title: 'Cartaz de Oferta De/Por Grátis | Ofertamática',
    description: 'Crie cartaz De/Por com preço anterior e preço de promoção em destaque. Revise o desconto e imprima placas de oferta para o mercado.',
    keywords: 'cartaz de por, cartaz de por supermercado, placa de oferta de por, cartaz preço antigo preço novo',
    eyebrow: 'CARTAZ DE / POR',
    heading: 'Mostre o preço anterior sem perder o destaque da oferta',
    lead: 'Gere a placa normalmente e, depois, ative De/Por para incluir o preço anterior sem reconstruir o cartaz.',
    benefits: ['Preço anterior + preço oferta', 'Aplicação depois da geração', 'Prévia antes de imprimir'],
    tips: ['Deixe o preço novo como principal leitura.', 'Use o preço anterior apenas como referência.', 'Confirme se os dois valores pertencem à mesma unidade e gramatura.'],
    storeUse: ['Promoções temporárias com preço anterior.', 'Campanhas de redução de preço.', 'Comunicação em gôndola, ponta e ilha promocional.'],
  },
  {
    kind: 'seo',
    group: 'Preço',
    slug: 'cartaz-atacado-varejo',
    title: 'Cartaz Atacado e Varejo | Dois Preços para Imprimir',
    description: 'Crie placas com preço de atacado e de varejo no mesmo cartaz. Indique quantidade mínima, personalize e imprima para mercado e atacarejo.',
    keywords: 'cartaz atacado varejo, placa preço atacado varejo, cartaz atacarejo, preço atacado e varejo',
    eyebrow: 'ATACADO / VAREJO',
    heading: 'Dois preços na mesma comunicação, sem duplicar o trabalho',
    lead: 'Use o preço principal para varejo e informe o preço de atacado como condição adicional na mesma placa.',
    benefits: ['Atacado e varejo juntos', 'Edição por produto', 'Impressão no tamanho físico escolhido'],
    tips: ['Deixe claro qual preço exige quantidade ou condição.', 'Evite misturar unidades diferentes sem explicação.', 'Revise os dois valores antes de imprimir.'],
    storeUse: ['Atacarejos com duas faixas de preço.', 'Mercados com condição por volume.', 'Ilhas e pontas com comunicação de compra em quantidade.'],
  },
  {
    kind: 'seo',
    group: 'Guias',
    slug: 'como-fazer-cartaz-de-oferta',
    title: 'Como Fazer Placas de Preço para Mercado | Guia Grátis',
    description: 'Aprenda como fazer cartazes de supermercado com produto, unidade, preço grande e impressão correta. Use o criador online grátis.',
    keywords: 'como fazer cartaz de oferta, como criar cartaz de preço, modelo cartaz oferta, fazer placa promoção',
    eyebrow: 'GUIA PRÁTICO',
    heading: 'Como fazer um cartaz de oferta claro e profissional',
    lead: 'Organize a descrição, destaque preço e unidade, escolha o formato pela distância de leitura e mantenha um padrão entre as ofertas.',
    benefits: ['Descrição curta e reconhecível', 'Preço e unidade com hierarquia clara', 'Formato adequado ao ponto de exposição'],
    tips: ['Comece pela informação que o cliente precisa reconhecer.', 'Deixe o preço como maior elemento do cartaz.', 'Mantenha campanhas da mesma ação visualmente consistentes.'],
  },
]

export const INDEXABLE_PAGES = [...PUBLIC_PAGES, ...SEO_PAGES]

export const SEO_FAQS = [
  { q: 'O Ofertamática serve para supermercado?', a: 'Sim. O editor foi pensado para rotinas de ofertas de supermercados, mercados, atacarejos, mercearias, hortifrutis, padarias, açougues e outros negócios do varejo.' },
  { q: 'Quais formatos posso imprimir?', a: 'O editor oferece A4, A5 e A3, além de opções A4 com dois ou quatro cartazes por folha.' },
  { q: 'Consigo criar vários cartazes de uma vez?', a: 'Sim. Você pode colar uma lista com vários produtos, revisar os dados e gerar as placas no mesmo fluxo.' },
  { q: 'Posso importar produtos de planilha?', a: 'Sim. O editor aceita importação compatível e também permite colar os produtos diretamente na entrada rápida.' },
  { q: 'Preciso instalar algum programa?', a: 'Não. O Ofertamática funciona direto no navegador. Em navegadores compatíveis, você pode instalar o site como app opcional para abrir mais rápido no computador ou celular da loja.' },
  { q: 'Posso colocar a logo da minha loja?', a: 'Sim. A logo pode ser adicionada como personalização opcional e fica salva localmente no dispositivo para facilitar os próximos trabalhos.' },
  { q: 'Posso usar meu próprio header ou arte de campanha?', a: 'Sim. Depois de gerar a placa, você pode enviar um header próprio em PNG, JPG ou WebP. A arte fica salva localmente no dispositivo e pode ser trocada a qualquer momento.' },
  { q: 'Consigo salvar os cartazes em PDF?', a: 'Sim. O editor oferece a opção Salvar PDF e abre a janela de impressão para escolher “Salvar como PDF”, preservando o tamanho físico configurado.' },
  { q: 'Preciso fazer cadastro para começar?', a: 'Não. O fluxo atual permite começar gratuitamente e sem cadastro obrigatório.' },
  { q: 'Dá para ter a primeira placa pronta em 2 cliques?', a: 'Sim. No fluxo principal, o primeiro clique escolhe o formato. Se a lista já estiver copiada, o segundo pode usar “Colar e gerar”. Também é possível colar manualmente ou importar arquivo. Personalização é opcional e vem depois.' },
  { q: 'Quais tipos de oferta posso usar?', a: 'Além do cartaz padrão, o editor oferece De/Por, Leve X por Y, Atacado/Varejo, Clube/App e 2ª unidade como opções de personalização depois da geração.' },
]

export const SEO_TOPIC_GROUPS = [
  { title: 'Para o seu negócio', items: ['Supermercado', 'Mercado', 'Atacarejo', 'Mercearia', 'Hortifruti', 'Padaria', 'Açougue', 'Farmácia'] },
  { title: 'Para suas campanhas', items: ['Oferta padrão', 'De / Por', 'Leve X por Y', 'Atacado / Varejo', 'Clube / App', '2ª unidade', 'Oferta relâmpago', 'Fim de semana', 'Black Friday', 'Natal', 'Páscoa'] },
  { title: 'Para seus setores', items: ['Bebidas', 'Hortifruti', 'Açougue', 'Padaria', 'Frios e laticínios', 'Limpeza', 'Higiene e beleza'] },
]

export const PAGE_BY_PATH = Object.fromEntries(
  INDEXABLE_PAGES.map((page) => [`/${page.slug}`, page]),
)
