// Fonte única de conteúdo/SEO para runtime, sitemap e páginas estáticas.
// PRODUCT_DECISION_AI_UPCOMING: IA é próxima implementação; não anunciar como recurso disponível.
export const SITE_URL = 'https://ofertamatica.com.br'

export const PUBLIC_PAGES = [
  {
    kind: 'public',
    slug: 'modelos',
    title: 'Modelos de Cartaz de Oferta | Ofertamática',
    description: 'Conheça modelos de cartaz de oferta para supermercado e varejo e personalize cores, cabeçalho e conteúdo no Ofertamática.',
    keywords: 'modelos de cartaz de oferta, modelo cartaz supermercado, modelo placa de preço',
    eyebrow: 'MODELOS',
    heading: 'Modelos para destacar cada tipo de oferta',
    lead: 'Escolha uma base visual e adapte cores, cabeçalho e conteúdo para a campanha ou departamento da sua loja.',
    benefits: ['Quatro estilos rápidos', 'Cores e cabeçalhos personalizáveis', 'Aplicação direta no editor'],
  },
  {
    kind: 'public',
    slug: 'formatos',
    title: 'Formatos de Cartaz A4, A5, A3 e SRA3 | Ofertamática',
    description: 'Compare A4, A5, A3 e SRA3, além de opções com vários cartazes por folha, e escolha o formato ideal para imprimir ofertas.',
    keywords: 'formato cartaz A4, cartaz A5, cartaz A3, cartaz SRA3, tamanho cartaz oferta',
    eyebrow: 'FORMATOS',
    heading: 'Escolha o formato certo para cada espaço da loja',
    lead: 'Compare tamanho físico, quantidade por folha e distância de leitura antes de iniciar a criação.',
    benefits: ['A4 com 1, 2 ou 4 cartazes', 'A5, A3 e SRA3', 'Pré-visualização antes da impressão'],
  },
  {
    kind: 'public',
    slug: 'como-funciona',
    title: 'Como Funciona o Ofertamática | Criar Cartazes de Oferta',
    description: 'Veja como criar cartazes no Ofertamática: escolha o formato, adicione produtos, personalize, revise e imprima.',
    keywords: 'como criar cartaz de oferta, como funciona Ofertamática, criar placa de preço',
    eyebrow: 'COMO FUNCIONA',
    heading: 'Da lista de produtos ao cartaz pronto para imprimir',
    lead: 'Um fluxo direto para escolher o papel, revisar os produtos, personalizar o visual e conferir a impressão.',
    benefits: ['Fluxo em quatro etapas', 'Trabalho salvo no dispositivo', 'Revisão antes da impressão'],
  },
  {
    kind: 'public',
    slug: 'guias-para-varejo',
    title: 'Guias para Varejo e Cartazes de Oferta | Ofertamática',
    description: 'Acesse guias práticos sobre cartazes de supermercado, promoções, preços, formatos e impressão para o varejo.',
    keywords: 'guias varejo, cartaz supermercado, cartaz promoção, cartaz para imprimir',
    eyebrow: 'GUIAS PARA VAREJO',
    heading: 'Guias práticos para melhorar a comunicação de ofertas',
    lead: 'Conteúdos organizados por criação, supermercado, campanhas, preço, impressão e inteligência artificial.',
    benefits: ['Conteúdo por necessidade', 'Links internos organizados', 'Acesso direto ao criador'],
  },
]

export const SEO_PAGES = [
  {
    kind: 'seo',
    group: 'Criação',
    slug: 'criador-de-cartaz-de-oferta',
    title: 'Criador de Cartaz de Oferta Grátis | Ofertamática',
    description: 'Crie cartazes de oferta online, escolha o formato, informe produtos, personalize e revise a impressão no Ofertamática.',
    keywords: 'criador de cartaz de oferta, criar cartaz de oferta, cartaz promocional, placa de oferta',
    eyebrow: 'CRIADOR DE CARTAZ DE OFERTA',
    heading: 'Crie cartazes de oferta prontos para imprimir',
    lead: 'Monte placas promocionais com um fluxo simples: escolha o formato, adicione os produtos, revise e imprima.',
    benefits: ['Formatos físicos para varejo', 'Vários cartazes por folha', 'Edição de preço, texto, cores e cabeçalho'],
    tips: ['Escolha o formato pela distância de leitura.', 'Mantenha a descrição curta e reconhecível.', 'Revise preço e unidade antes de imprimir.'],
  },
  {
    kind: 'seo',
    group: 'Supermercado',
    slug: 'cartaz-para-supermercado',
    title: 'Cartaz para Supermercado | Crie e Imprima Online',
    description: 'Crie cartazes de preço e promoção para supermercados, mercados, mercearias e atacarejos com o Ofertamática.',
    keywords: 'cartaz para supermercado, cartaz supermercado, cartaz para mercado, placa de preço supermercado',
    eyebrow: 'CARTAZ PARA SUPERMERCADO',
    heading: 'Cartazes de supermercado sem perder tempo formatando',
    lead: 'Organize ofertas para gôndolas, hortifruti, açougue, padaria, bebidas e outros setores em um padrão visual consistente.',
    benefits: ['Preço em destaque', 'Cabeçalhos por campanha ou setor', 'Fluxo pensado para várias ofertas'],
    tips: ['Use cartazes menores para gôndola e maiores para ponta/vitrine.', 'Agrupe campanhas por setor para manter consistência.', 'Evite excesso de texto concorrendo com o preço.'],
  },
  {
    kind: 'seo',
    group: 'Campanhas',
    slug: 'gerador-de-cartaz-de-promocao',
    title: 'Gerador de Cartaz de Promoção Online | Ofertamática',
    description: 'Gere cartazes promocionais para ofertas do dia, fim de semana, campanhas e ações sazonais.',
    keywords: 'gerador de cartaz de promoção, cartaz de promoção online, criar promoção, cartaz promocional',
    eyebrow: 'GERADOR DE CARTAZ DE PROMOÇÃO',
    heading: 'Transforme sua lista de promoções em cartazes',
    lead: 'Crie comunicação promocional clara para ofertas recorrentes e campanhas sazonais sem começar o layout do zero.',
    benefits: ['Criação em lote', 'Cabeçalhos promocionais', 'Formatos para diferentes pontos da loja'],
    tips: ['Use um cabeçalho coerente com a campanha.', 'Destaque uma condição promocional por cartaz.', 'Padronize os cartazes da mesma ação.'],
  },
  {
    kind: 'seo',
    group: 'Preço',
    slug: 'cartaz-de-preco-online',
    title: 'Cartaz de Preço Online | Crie e Imprima no Ofertamática',
    description: 'Crie cartaz de preço online com descrição, unidade, gramatura e valor em destaque, direto no navegador.',
    keywords: 'cartaz de preço online, placa de preço, criar cartaz de preço, preço para imprimir',
    eyebrow: 'CARTAZ DE PREÇO ONLINE',
    heading: 'Preço legível e produto fácil de identificar',
    lead: 'Organize produto, complemento, unidade e valor com uma hierarquia visual pensada para leitura rápida.',
    benefits: ['Preço com destaque automático', 'Campos editáveis', 'Pré-visualização antes da impressão'],
    tips: ['Confira se unidade e gramatura correspondem ao preço.', 'Evite abreviações pouco conhecidas.', 'Use contraste forte entre fundo e preço.'],
  },
  {
    kind: 'seo',
    group: 'Criação',
    slug: 'cartaz-de-oferta-gratis',
    title: 'Cartaz de Oferta Grátis | Crie Online com Ofertamática',
    description: 'Crie cartazes e placas de oferta grátis no navegador, sem cadastro obrigatório para começar.',
    keywords: 'cartaz de oferta grátis, fazer cartaz de oferta grátis, cartaz grátis, criar placa de oferta grátis',
    eyebrow: 'CARTAZ DE OFERTA GRÁTIS',
    heading: 'Comece seu cartaz de oferta sem cadastro',
    lead: 'Escolha um formato, adicione os produtos e prepare a impressão diretamente no navegador.',
    benefits: ['Uso gratuito', 'Sem cadastro obrigatório para começar', 'Editor direto no navegador'],
    tips: ['Comece pelo formato que sua impressora suporta.', 'Cole vários produtos de uma vez para ganhar tempo.', 'Use a prévia para revisar antes de imprimir.'],
  },
  {
    kind: 'seo',
    group: 'Supermercado',
    slug: 'cartaz-supermercado-online',
    title: 'Cartaz de Supermercado Online | Ofertamática',
    description: 'Crie cartazes de supermercado online para ofertas, preços e campanhas, personalize e imprima em poucos passos.',
    keywords: 'cartaz supermercado online, criar cartaz supermercado, ofertas supermercado, placa supermercado',
    eyebrow: 'SUPERMERCADO ONLINE',
    heading: 'Sua comunicação de ofertas em um só lugar',
    lead: 'Monte cartazes para ações semanais, oferta relâmpago, feira, açougue, bebidas, higiene e outras rotinas do supermercado.',
    benefits: ['Criação rápida', 'Padronização visual', 'Biblioteca de cabeçalhos'],
    tips: ['Crie padrões por departamento.', 'Use nomes de produto fáceis de reconhecer.', 'Escolha o tamanho conforme o local de exposição.'],
  },
  {
    kind: 'seo',
    group: 'Impressão',
    slug: 'cartaz-de-oferta-para-imprimir',
    title: 'Cartaz de Oferta para Imprimir | A4, A5, A3 e SRA3',
    description: 'Prepare cartazes de oferta para imprimir com tamanho físico, orientação e quantidade por folha.',
    keywords: 'cartaz de oferta para imprimir, cartaz A4 para imprimir, placa de oferta imprimir, cartaz A3',
    eyebrow: 'CARTAZ PARA IMPRIMIR',
    heading: 'Crie no navegador e imprima no tamanho certo',
    lead: 'Escolha o papel, confira a orientação e revise o resultado visual antes de abrir a janela de impressão.',
    benefits: ['A4, A5, A3 e SRA3', '1, 2 ou 4 cartazes por folha no A4', 'Revisão de impressão integrada'],
    tips: ['Use escala de 100% na impressão.', 'Desative cabeçalhos e rodapés do navegador.', 'Confira papel e orientação antes de confirmar.'],
  },
  {
    kind: 'seo',
    group: 'Impressão',
    slug: 'cartaz-a4',
    title: 'Cartaz A4 de Oferta | Crie e Imprima Online',
    description: 'Crie cartaz A4 de oferta online e use uma folha inteira ou modelos com dois ou quatro cartazes por folha.',
    keywords: 'cartaz A4, cartaz A4 oferta, cartaz A4 para imprimir, placa de preço A4',
    eyebrow: 'FORMATO A4',
    heading: 'Cartazes A4 para diferentes espaços da loja',
    lead: 'Use uma folha inteira para maior impacto ou aproveite o A4 com duas ou quatro placas menores.',
    benefits: ['A4 com 1 cartaz', 'A4 com 2 cartazes', 'A4 com 4 cartazes'],
    tips: ['A4 inteiro funciona melhor à distância.', 'Dois por folha equilibram impacto e economia.', 'Quatro por folha funcionam melhor em leitura próxima.'],
  },
  {
    kind: 'seo',
    group: 'IA',
    slug: 'gerador-de-cartaz-com-ia',
    title: 'Gerador de Cartaz com IA — em breve | Ofertamática',
    description: 'Conheça a próxima implementação do Ofertamática: criação de cartazes com IA para interpretar produtos e reduzir ajustes manuais.',
    keywords: 'gerador de cartaz com IA, cartaz com inteligência artificial, criar cartaz com IA, IA para supermercado',
    eyebrow: 'PRÓXIMA IMPLEMENTAÇÃO · IA',
    heading: 'Crie seu cartaz com IA',
    lead: 'Estamos preparando inteligência artificial para interpretar produtos, organizar informações e acelerar a rotina de criação. O editor atual continua disponível.',
    benefits: ['Interpretação inteligente de produtos', 'Menos ajustes manuais', 'Revisão humana antes da impressão'],
    tips: ['A IA será um acelerador, não uma etapa obrigatória.', 'O usuário continuará podendo revisar os campos.', 'A impressão continuará passando pela prévia final.'],
    comingSoon: true,
  },
  {
    kind: 'seo',
    group: 'Guias',
    slug: 'como-fazer-cartaz-de-oferta',
    title: 'Como Fazer Cartaz de Oferta | Guia Prático',
    description: 'Veja como fazer um cartaz de oferta com produto, unidade e preço bem destacados e crie suas placas no Ofertamática.',
    keywords: 'como fazer cartaz de oferta, como criar cartaz de preço, modelo cartaz oferta, fazer placa promoção',
    eyebrow: 'GUIA PRÁTICO',
    heading: 'Como fazer um cartaz de oferta claro e profissional',
    lead: 'Organize a descrição, destaque preço e unidade, escolha o formato pela distância de leitura e mantenha um padrão entre as ofertas.',
    benefits: ['Descrição curta e reconhecível', 'Preço e unidade com hierarquia clara', 'Formato adequado ao ponto de exposição'],
    tips: ['Comece pela informação que o cliente precisa reconhecer.', 'Deixe o preço como maior elemento do cartaz.', 'Mantenha campanhas da mesma ação visualmente consistentes.'],
  },
]

export const INDEXABLE_PAGES = [...PUBLIC_PAGES, ...SEO_PAGES]

export const SEO_FAQS = [
  { q: 'O Ofertamática serve para supermercado?', a: 'Sim. O editor foi pensado para rotinas de ofertas de supermercados, mercados, atacarejos, mercearias, hortifrutis, padarias, açougues e outros negócios do varejo.' },
  { q: 'Quais formatos posso imprimir?', a: 'O editor oferece A4, A5, A3 e SRA3, além de opções A4 com dois ou quatro cartazes por folha.' },
  { q: 'Consigo criar vários cartazes de uma vez?', a: 'Sim. Você pode colar uma lista com vários produtos, revisar os dados e gerar as placas no mesmo fluxo.' },
  { q: 'Posso importar produtos de planilha?', a: 'Sim. O editor aceita importação compatível e também permite colar os produtos diretamente na entrada rápida.' },
  { q: 'Preciso instalar algum programa?', a: 'Não. O Ofertamática funciona no navegador e a criação, revisão e impressão acontecem online.' },
  { q: 'Preciso fazer cadastro para começar?', a: 'Não. O fluxo atual permite começar gratuitamente e sem cadastro obrigatório.' },
  { q: 'O site já cria cartaz com IA?', a: 'Ainda não. “Crie seu cartaz com IA” é a próxima implementação. O editor atual já permite criar, personalizar, revisar e imprimir cartazes.' },
]

export const SEO_TOPIC_GROUPS = [
  { title: 'Para o seu negócio', items: ['Supermercado', 'Mercado', 'Atacarejo', 'Mercearia', 'Hortifruti', 'Padaria', 'Açougue', 'Farmácia'] },
  { title: 'Para suas campanhas', items: ['Oferta relâmpago', 'Promoção do dia', 'Fim de semana', 'Ofertas da semana', 'Black Friday', 'Natal', 'Páscoa'] },
  { title: 'Para seus setores', items: ['Bebidas', 'Hortifruti', 'Açougue', 'Padaria', 'Frios e laticínios', 'Limpeza', 'Higiene e beleza'] },
]

export const PAGE_BY_PATH = Object.fromEntries(
  INDEXABLE_PAGES.map((page) => [`/${page.slug}`, page]),
)
